[workspace]
resolver = "2"
members = [
    "counter",
    "temperature-converter",
    "flight-booker",
    "timer",
    "crud",
    "circle-drawer",
    "cells",
]

[workspace.dependencies]
iced = "0.14"
